- alias: Set light scene
  trigger:
    platform: state
    entity_id: input_select.scene
  action:
    - service: script.turn_on
      entity_id: script.notify
      data_template:
        variables:
          message: "Scene: {{ states('input_select.scene') }}"
    - service: light.hue_activate_scene
      data_template:
        group_name: Lounge
        scene_name: "{{ states('input_select.scene') }}"

- alias: Arm alarm (timed)
  trigger:
    platform: time
    after: "09:00:00"
  condition:
    condition: and
    conditions:
      - condition: time
        weekday:
          - mon
          - tue
          - thu
  action:
    - service: script.turn_on
      entity_id: script.notify
      data:
        variables:
          message: "Activating alarm by schedule"
    - service: alarm_control_panel.alarm_arm_away

- alias: Arming set
  trigger:
    platform: state
    entity_id: alarm_control_panel.ha_alarm
    state: armed_away
  action:
    - service: script.turn_on
      entity_id: script.notify
      data:
        variables:
          message: "Alarm is enabled"

- alias: Disarm alarm (timed)
  trigger:
    platform: time
    after: "18:00:00"
  condition:
    condition: and
    conditions:
      - condition: time
        weekday:
          - mon
          - tue
          - thu
  action:
    - service: script.turn_on
      entity_id: script.notify
      data:
        variables:
          message: "Alarm is disarmed by schedule"
    - service: alarm_control_panel.alarm_disarm

- alias: Trigger alarm if motion downstairs
  trigger:
    platform: state
    entity_id: sensor.aeotec_zw100_multisensor_6_burglar_2_10
    from: "0"
    to: "8"
  condition:
    - condition: state
      entity_id: alarm_control_panel.ha_alarm
      state: armed_away
  action:
    - service: script.turn_on
      entity_id: script.notify
      data:
        variables:
          message: "Alarm"
    - service: alarm_control_panel.alarm_trigger


