- alias: Set light scene
  trigger:
    platform: state
    entity_id: input_select.scene
  action:
    - service: script.turn_on
      entity_id: script.notify
      data_template:
        variables:
          message: "Scene: {{ states('input_select.scene') }}"
    - service: light.hue_activate_scene
      data_template:
        group_name: Lounge
        scene_name: "{{ states('input_select.scene') }}"

- alias: Arm alarm (timed)
  trigger:
    platform: time
    after: "09:00:00"
  condition:
    condition: and
    conditions:
      - condition: time
        weekday:
          - mon
          - tue
          - thu
  action:
    - service: script.turn_on
      entity_id: script.notify
      data:
        variables:
          message: "Activating alarm by schedule"
    - service: alarm_control_panel.alarm_arm_away

- alias: Arming set
  trigger:
    platform: state
    entity_id: alarm_control_panel.ha_alarm
    state: armed_away
  action:
    - service: script.turn_on
      entity_id: script.notify
      data:
        variables:
          message: "Alarm is enabled"

- alias: Disarm alarm (timed)
  trigger:
    platform: time
    after: "18:30:00"
  condition:
    condition: and
    conditions:
      - condition: time
        weekday:
          - mon
          - tue
          - thu
  action:
    - service: script.turn_on
      entity_id: script.notify
      data:
        variables:
          message: "Alarm is disarmed by schedule"
    - service: alarm_control_panel.alarm_disarm

- alias: Trigger alarm if motion downstairs
  trigger:
    platform: state
    entity_id: binary_sensor.zw100_sensor_2_0
    to: "on"
  condition:
    - condition: state
      entity_id: alarm_control_panel.ha_alarm
      state: armed_away
  action:
    - service: script.turn_on
      entity_id: script.notify
      data:
        variables:
          message: "Alarm"
    - service: alarm_control_panel.alarm_trigger

- alias: Turn off lights on work day mornings
  trigger:
    platform: time
    after: "09:00:00"
  action:
    - service: homeassistant.turn_off
      entity_id:
        - group.house

- alias: Set evening lighting scene
  trigger:
    platform: sun
    event: sunset
  action:
    - service: light.hue_activate_scene
      data:
        group_name: Lounge
        scene_name: Relax
    - service: light.hue_activate_scene
      data:
        group_name: Kitchen
        scene_name: Relax

- alias: Keep hallway light on and dimmed all evening
  trigger:
    platform: time
    minutes: "/5"
  condition:
    - condition: sun
      after: sunset
  action:
    - service: light.turn_on
      data:
        entity_id: light.hallway_downstairs_colour
        color_name: red
        brightness: 10

- alias: Turn off downstairs lights in evening on workdays
  trigger:
    platform: time
    after: "23:30:00"
  condition:
    condition: and
    conditions:
      - condition: time
        weekday:
          - sun
          - mon
          - tue
          - wed
          - thu
  action:
    - service: homeassistant.turn_off
      entity_id:
        - group.downstairs

- alias: Turn off downstairs lights later in evening on weekends
  trigger:
    platform: time
    after: "01:00:00"
  condition:
    condition: and
    conditions:
      - condition: time
        weekday:
          - sat
          - sun
  action:
    - service: homeassistant.turn_off
      entity_id:
        - group.downstairs
        - light.outside_front

- alias: Turn on outside light after sunset
  trigger:
    platform: sun
    event: sunset
  action:
    - service: homeassistant.turn_on
      entity_id:
        - light.outside_front

