- platform: mjpeg
  name: lounge
  mjpeg_url: http://docker.home:44401

- platform: mjpeg
  name: back
  mjpeg_url: http://docker.home:44402

- platform: mjpeg
  name: front
  mjpeg_url: http://docker.home:44403
