default_config:
http:
  base_url: !secret base_url

automation: !include automations.yaml
group: !include groups.yaml
binary_sensor: !include binary_sensor.yaml
sensor: !include sensor.yaml
script: !include scripts.yaml
switch: !include switch.yaml

blink:
  username: !secret blink_username
  password: !secret blink_password

frontend:
  themes: !include_dir_merge_named ./themes

google:
  client_id: !secret gcal_client_id
  client_secret: !secret gcal_client_secret

hue:
  bridges:
    - host: "hue-lounge.home"
      allow_unreachable: true
      allow_hue_groups: false

ifttt:
  key: !secret ifttt_api_key

influxdb:
  host: d1.home
  username: user
  password: user
  database: hass

mqtt:
  broker: !secret cloudmqtt_broker
  port: !secret cloudmqtt_port
  username: !secret cloudmqtt_username
  password: !secret cloudmqtt_password

notify:
  - name: slack
    platform: slack
    api_key: !secret slack_api_key
    default_channel: '#house'

person:
  - name: Louis
    id: d7401544969b488197b0a0d02000ec7e
    device_trackers:
      - device_tracker.phone_louis

remote:
  - platform: harmony
    name: Lounge
    host: "harmony-lounge.home"

speedtestdotnet:
  server_id: 26075

tts:
  - platform: google_translate
    base_url: !secret tts_base_url


