
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

lovelace:
  mode: yaml
  #dashboards:
  #  lovelace-test:
  #    mode: yaml
  #    title: YAML
  #    icon: mdi:script
  #    show_in_sidebar: true
  #    filename: lovelace.yaml