homeassistant:
  name: Home
  unit_system: metric
  time_zone: Europe/London
  customize: !include customize.yaml

frontend:
updater:
discovery:
conversation:
history:
logbook:
sun:

alarm_control_panel: !include alarm_control_panel.yaml
automation: !include automation.yaml
device_tracker: !include device_tracker.yaml
google: !include google.yaml
group: !include group.yaml
http: !include http.yaml
ifttt: !include ifttt.yaml
input_select: !include input_select.yaml
joaoapps_join: !include joaoapps_join.yaml
light: !include light.yaml
mqtt: !include mqtt.yaml
notify: !include notify.yaml
proximity: !include proximity.yaml
remote: !include remote.yaml
script: !include script.yaml
sensor: !include sensor.yaml
zone: !include zone.yaml
zwave: !include zwave.yaml
