homeassistant:
  name: Home
  unit_system: metric
  time_zone: Europe/London
  customize: !include customize.yaml

frontend:
updater:
discovery:
conversation:
history:
logbook:
sun:
tts_service:

alarm_control_panel: !include alarm_control_panel.yaml
apcupsd: !include apcupsd.yaml
automation: !include_dir_merge_list automation
camera: !include camera.yaml
device_tracker: !include device_tracker.yaml
google: !include google.yaml
group: !include group.yaml
http: !include http.yaml
ifttt: !include ifttt.yaml
influxdb: !include influxdb.yaml
input_select: !include input_select.yaml
joaoapps_join: !include joaoapps_join.yaml
logger: !include logger.yaml
light: !include light.yaml
mqtt: !include mqtt.yaml
notify: !include notify.yaml
proximity: !include proximity.yaml
#remote: !include remote.yaml
script: !include_dir_named scripts
sensor: !include sensor.yaml
switch: !include switch.yaml
tts: !include tts.yaml
zone: !include zone.yaml
zwave: !include zwave.yaml
