#- platform: ping
#  track_new_devices: false
#  count: 3
#  consider_home: 30
#  interval: 5
#  hosts:
#    louis_phone: !secret ip_louis_phone
#    sarah_phone: !secret ip_sarah_phone

- platform: owntracks
  max_gps_accuracy: 200
  track_new_devices: true
