- platform: google_travel_time
  name: IPS to CBG
  api_key: !secret google_transit_api_key
  origin: zone.home
  destination: !secret office_louis
  options:
    departure_time: 08:00:00
    mode: transit
    transit_mode: rail
    units: imperial

- platform: google_travel_time
  name: IPS to CHM
  api_key: !secret google_transit_api_key
  origin: zone.home
  destination: !secret office_sarah
  options:
    departure_time: 08:30:00
    mode: transit
    transit_mode: rail
    units: imperial

- platform: yr
  monitored_conditions:
    - temperature
    - symbol
    - precipitation
    - windSpeed   

