- platform: darksky
  api_key: !secret darksky_api_key
  units: uk2
  monitored_conditions:
    - summary
    - icon
    - precip_type
    - precip_intensity
    - precip_probability
    - temperature
    - apparent_temperature
    - wind_speed
    - wind_gust
    - visibility
