- platform: template
  switches:
    watch_lounge_sky_tv:
      friendly_name: Sky TV
      value_template: "{{ is_state_attr('remote.lounge', 'current_activity', 'Sky TV') }}"
      turn_on:
        service: remote.turn_on
        data:
          entity_id: remote.lounge
          activity: '42860933'
      turn_off:
        service: remote.turn_off
        data:
          entity_id: remote.lounge
          activity: '-1'
- platform: template
  switches:
    watch_lounge_shield:
      friendly_name: Shield
      value_template: "{{ is_state_attr('remote.lounge', 'current_activity', 'Shield') }}"
      turn_on:
        service: remote.turn_on
        data:
          entity_id: remote.lounge
          activity: 'Shield'
      turn_off:
        service: remote.turn_off
        data:
          entity_id: remote.lounge
          activity: 'PowerOff'
- platform: template
  switches:
    watch_lounge_switch:
      friendly_name: Switch
      value_template: "{{ is_state_attr('remote.lounge', 'current_activity', 'Switch') }}"
      turn_on:
        service: remote.turn_on
        data:
          entity_id: remote.lounge
          activity: 'Switch'
      turn_off:
        service: remote.turn_off
        data:
          entity_id: remote.lounge
          activity: 'PowerOff'

