- alias: Disarm alarm (facial recognition)
  trigger:
    platform: event
    event_type: image_processing.detect_face
    event_data:
      entity_id: image_processing.microsoftface_lounge
      name: louis
  condition:
    - condition: state
      entity_id: alarm_control_panel.house
      state: armed_away
  action:
    - service: notify.residents
      data:
        message: "Recognised Louis' face"
    - service: alarm_control_panel.alarm_disarm
      entity_id: alarm_control_panel.house
      data:
        code: !secret alarm_code

- alias: Alarm triggered
  trigger:
    platform: state
    entity_id: alarm_control_panel.house
    to: triggered
  action:
    - service: notify.residents
      data:
        message: "Unauthorised entry! The residents have been informed!"
    - service: light.turn_on
      entity_id: group.alarm_lights
      data:
        flash: long
 
