- alias: Morning
  trigger:
    platform: time
    after: '09:00:00'
  action:
    - service: media_player.volume_set
      data:
        entity_id: media_player.portable
        volume_level: 0.6
    - service: script.announce

- alias: Evening
  trigger:
    platform: time
    after: '20:00:00'
  action:
    - service: media_player.volume_set
      data:
        entity_id: media_player.portable
        volume_level: 0.4

- alias: Night
  trigger:
    platform: time
    after: '22:00:00'
  action:
    - service: media_player.volume_set
      data:
        entity_id: media_player.portable
        volume_level: 0.2
