- alias: Set light scene
  trigger:
    platform: state
    entity_id: input_select.scene
  action:
    - service: script.turn_on
      entity_id: script.notify
      data_template:
        variables:
          message: "Scene: {{ states('input_select.scene') }}"
    - service: light.hue_activate_scene
      data_template:
        group_name: Lounge
        scene_name: "{{ states('input_select.scene') }}"

- alias: Set evening lighting scene
  trigger:
    platform: sun
    event: sunset
  condition:
    - condition: state
      entity_id: group.residents
      state: not_home
  action:
    - service: light.hue_activate_scene
      data:
        group_name: Lounge
        scene_name: Relax
    - service: light.hue_activate_scene
      data:
        group_name: Kitchen
        scene_name: Relax

- alias: Turn off downstairs lights (and subwoofer) in evening on workdays
  trigger:
    platform: time
    after: "23:30:00"
  condition:
    condition: and
    conditions:
      - condition: time
        weekday:
          - sun
          - mon
          - tue
          - wed
          - thu
  action:
    - service: homeassistant.turn_off
      entity_id:
        - group.downstairs
        - group.loud_things

- alias: Turn off downstairs lights (and subwoofer) later in evening on weekends
  trigger:
    platform: time
    after: "01:00:00"
  condition:
    condition: and
    conditions:
      - condition: time
        weekday:
          - sat
          - sun
  action:
    - service: homeassistant.turn_off
      entity_id:
        - group.downstairs
        - group.loud_things

- alias: Turn on outside light after sunset
  trigger:
    platform: sun
    event: sunset
  action:
    - service: homeassistant.turn_on
      entity_id:
        - group.outside

- alias: Turn off outside light during the evening
  trigger:
    platform: time
    after: "21:00:00"
  action:
    - service: homeassistant.turn_off
      entity_id:
        - group.outside


