- trigger:
    platform: state
    entity_id: switch.moodswitch_hallway
    state: "on"
  action:
    - service: input_boolean.turn_on
      entity_id: input_boolean.away

- trigger:
    platform: state
    entity_id: switch.moodswitch_hallway
    state: "off"
  action:
    - service: input_boolean.turn_off
      entity_id: input_boolean.away

- trigger:
    platform: state
    entity_id: switch.remote_a1
    state: "on"
  action:
    - service: homeassistant.turn_on
      entity_id: group.living_area

- trigger:
    platform: state
    entity_id: switch.remote_a1
    state: "off"
  action:
    - service: homeassistant.turn_off
      entity_id:
        - group.living_area
        - group.loud_things

- alias: Announcement
  trigger:
    platform: state
    entity_id: switch.remote_a4
    state: "on"
  action:
    - service: script.turn_on
      entity_id: script.announce


