- alias: Living lights on
  trigger:
    platform: state
    entity_id: switch.remote_a1
    state: "on"
  action:
    - service: homeassistant.turn_on
      entity_id: group.living_area

- alias: Living lights off
  trigger:
    platform: state
    entity_id: switch.remote_a1
    state: "off"
  action:
    - service: homeassistant.turn_off
      entity_id: group.living_area

