- alias: Trigger alarm if motion downstairs
  trigger:
    platform: state
    entity_id: sensor.aeotec_zw100_multisensor_6_burglar_2_10
    from: "0"
    to: "8"
  condition:
    condition: or
    conditions:
      - condition: state
        entity_id: alarm_control_panel.house
        state: armed_away
      - condition: state
        entity_id: alarm_control_panel.house
        state: armed_home
  action:
    - service: alarm_control_panel.alarm_trigger
      entity_id: alarm_control_panel.house

