# AUTOMATION OVERRIDE

- alias: Override enabled
  trigger:
    platform: state
    entity_id: input_boolean.override
    to: 'on'
  action:
    - service: notify.residents
      data:
        message: Manual override enabled. No further automation actions will occur until 6am tomorrow morning.
    - service: light.turn_on
      entity_id: group.flash_lights
      data:
        flash: short
 
- alias: Override disabled
  trigger:
    platform: state
    entity_id: input_boolean.override
    to: 'off'
  action:
    - service: notify.residents
      data:
        message: Manual override disabled. Normal operations will now resume.
    - service: light.turn_on
      entity_id: group.flash_lights
      data:
        flash: short
 
- alias: Override Timeout
  trigger:
    platform: time
    after: '06:00:00'
  action:
    - service: input_boolean.turn_off
      entity_id: input_boolean.override
