# MOOD SWITCH: FRONT DOOR

- trigger:
    platform: state
    entity_id: switch.moodswitch_door_front
    state: "on"
  action:
    - service: input_boolean.turn_on
      entity_id: input_boolean.away

- trigger:
    platform: state
    entity_id: switch.moodswitch_door_front
    state: "off"
  action:
    - service: input_boolean.turn_off
      entity_id: input_boolean.away

# MOOD SWITCH: LOUNGE

- trigger:
    platform: state
    entity_id: switch.moodswitch_lounge
    state: "on"
  action:
    - service: input_boolean.turn_on
      entity_id: input_boolean.lounge

- trigger:
    platform: state
    entity_id: switch.moodswitch_lounge
    state: "off"
  action:
    - service: input_boolean.turn_off
      entity_id: input_boolean.lounge

# MOOD SWITCH: STAIRS

- trigger:
    platform: state
    entity_id: switch.moodswitch_stairs
    state: "on"
  action:
    - service: input_boolean.turn_on
      entity_id: input_boolean.bedtime

- trigger:
    platform: state
    entity_id: switch.moodswitch_stairs
    state: "off"
  action:
    - service: input_boolean.turn_off
      entity_id: input_boolean.bedtime

# REMOTE: OLD

- trigger:
    platform: state
    entity_id: switch.remote_a1
    state: "on"
  action:
    - service: homeassistant.turn_on
      entity_id: group.living_area

- trigger:
    platform: state
    entity_id: switch.remote_a1
    state: "off"
  action:
    - service: homeassistant.turn_off
      entity_id:
        - group.living_area
        - group.loud_things

- trigger:
    platform: state
    entity_id: switch.remote_a2
    state: "on"
  action:
    - service: input_boolean.turn_on
      entity_id: input_boolean.override

- trigger:
    platform: state
    entity_id: switch.remote_a2
    state: "off"
  action:
    - service: input_boolean.turn_off
      entity_id: input_boolean.override

- alias: Announcement
  trigger:
    platform: state
    entity_id: switch.remote_a4
    state: "on"
  action:
    - service: script.turn_on
      entity_id: script.announce


