- alias: Set Away
  trigger:
    platform: state
    entity_id: switch.away
    state: "on"
  action:
    - service: script.turn_on
      entity_id: script.notify
      data:
        variables:
          message: "Residents are now considered away from home"
    - service: alarm_control_panel.alarm_arm_away
      entity_id: alarm_control_panel.house
      data:
        code: !secret alarm_code

- alias: Set Home
  trigger:
    platform: state
    entity_id: switch.away
    from: "on"
    to: "off"
  action:
    - service: script.turn_on
      entity_id: script.notify
      data:
        variables:
          message: "Residents are now considered home"



