# RESIDENTS AWAY FROM HOME

- alias: Away enabled
  trigger:
    platform: state
    entity_id: switch.moodswitch_door_front
    to: 'on'
  action:
    - service: script.turn_on
      entity_id: script.away_enabled

- alias: Away disabled
  trigger:
    platform: state
    entity_id: switch.moodswitch_door_front
    to: 'off'
  action:
    - service: script.turn_on
      entity_id: script.away_disabled

# RESIDENTS BEDTIME

- alias: Bedtime enabled
  trigger:
    platform: state
    entity_id: switch.moodswitch_stairs
    to: 'on'
  action:
    - service: script.turn_on
      entity_id: script.bedtime_enabled
          
- alias: Bedtime disabled
  trigger:
    platform: state
    entity_id: switch.moodswitch_stairs
    to: 'off'
  action:
    - service: script.turn_on
      entity_id: script.bedtime_disabled

# DOWNSTAIRS ACTIVE

- alias: Downstairs active enabled
  trigger:
    platform: state
    entity_id: switch.moodswitch_lounge
    to: 'on'
  action:
    - service: script.turn_on
      entity_id: script.downstairs_active_enabled
          
- alias: Downstairs active disabled
  trigger:
    platform: state
    entity_id: switch.moodswitch_lounge
    to: 'off'
  action:
    - service: script.turn_on
      entity_id: script.downstairs_active_disabled

